/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kth_number

fun getIdxK(array:IntArray, fromIdx:Int, toIdx:Int, K:Int):Int{
    return array.toList().subList(fromIdx-1,toIdx).sorted()[K-1]
}

fun getIdxKList(array: IntArray, commands: Array<IntArray>):IntArray{
    return commands.map { it -> getIdxK(array, it[0],it[1],it[2]) }.toIntArray()
}