/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.algorithm.test02

import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test
import kotlin.test.assertNotNull

fun solution(){

}


class AppTest {
   @Test
   fun `test`(){
       assertThat(solution())
   }
}
