/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kth_number

import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test

class AppTest {
    @Test fun testAppHasAGreeting() {
     //  assertThat(getIdxK(arrayListOf(1, 5, 2, 6, 3, 7, 4),2,5,3)).isEqualTo(5)
       assertThat(getIdxKList(intArrayOf(1, 5, 2, 6, 3, 7, 4),
               arrayOf(intArrayOf(2,5,3), intArrayOf(4,4,1), intArrayOf(1,7,3)))).isEqualTo(intArrayOf(5,6,3))
    }
}
